# Apuntamos al puerto 5433 que redirige hacia tu Ubuntu
spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/emotia
spring.datasource.username=admin
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Forzamos el dialecto para que Hibernate no intente adivinarlo si hay lag en el túnel
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true